group:
  - files:
      - source: templates/pull_request_template_frontend.md
        dest: .github/pull_request_template.md
    repos: |
      openmrs/openmrs-esm-admin-tools
      openmrs/openmrs-esm-billing-app
      openmrs/openmrs-esm-chartsearchai
      openmrs/openmrs-esm-clinical-views-builder
      openmrs/openmrs-esm-cohortbuilder-app
      openmrs/openmrs-esm-dispensing-app
      openmrs/openmrs-esm-draw-app
      openmrs/openmrs-esm-fast-data-entry-app
      openmrs/openmrs-esm-form-builder
      openmrs/openmrs-esm-form-engine-lib
      openmrs/openmrs-esm-laboratory-app
      openmrs/openmrs-esm-patient-chart
      openmrs/openmrs-esm-patient-communications
      openmrs/openmrs-esm-patient-management
      openmrs/openmrs-esm-stock-management
      openmrs/openmrs-esm-system-status
      openmrs/openmrs-esm-task-list
      openmrs/openmrs-esm-template-app
      openmrs/openmrs-esm-user-dashboard-widgets
      openmrs/openmrs-esm-user-onboarding
